definitions:
  dto.Account:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  dto.AccountAnswer:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      token:
        type: string
    type: object
  dto.CreateUser:
    properties:
      email:
        type: string
      name:
        maxLength: 30
        minLength: 2
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.Login:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.Token:
    properties:
      token:
        type: string
    type: object
  dto.UpdateUser:
    properties:
      email:
        type: string
      name:
        maxLength: 30
        minLength: 2
        type: string
      oldPassword:
        maxLength: 50
        minLength: 8
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    type: object
  resp.JsonError:
    properties:
      error:
        type: string
    type: object
  resp.Message:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /id/account/:
    get:
      description: Returns user own account.
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/dto.Account'
        "401":
          description: Unauth
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn`t found.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Retrieve user own account
      tags:
      - Account
  /id/account/{id}:
    get:
      consumes:
      - application/json
      description: Returns user information based on their ID.
      parameters:
      - description: user id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/dto.Account'
        "400":
          description: ID must be integer
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn`t found.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Retrieve user by ID
      tags:
      - Account
  /id/account/{id}/edit:
    patch:
      consumes:
      - application/json
      description: Updates the user's information including password. For admin
      parameters:
      - description: User update data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUser'
      - description: user id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Updated.
          schema:
            $ref: '#/definitions/dto.Account'
        "400":
          description: Incorrect data.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "401":
          description: Unauth
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn't found
          schema:
            $ref: '#/definitions/resp.JsonError'
        "409":
          description: User with this email already exists
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Update user information
      tags:
      - Account
  /id/account/all:
    get:
      description: List of users with pagination. Only for ADMIN
      parameters:
      - description: User update data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUser'
      - description: Page
        in: query
        name: page
        type: integer
      - description: Size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK.
          schema:
            items:
              $ref: '#/definitions/dto.Account'
            type: array
        "400":
          description: Incorrect data.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "401":
          description: Unauth
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn't found
          schema:
            $ref: '#/definitions/resp.JsonError'
        "409":
          description: User with this email already exists
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Get list of users
      tags:
      - Account
  /id/account/edit:
    patch:
      consumes:
      - application/json
      description: Updates the user's information including password.
      parameters:
      - description: User update data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: Updated.
          schema:
            $ref: '#/definitions/dto.Account'
        "400":
          description: Incorrect data.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "401":
          description: Unauth
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn't found
          schema:
            $ref: '#/definitions/resp.JsonError'
        "409":
          description: User with this email already exists
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Update user information
      tags:
      - Account
  /id/account/email/{email}:
    get:
      consumes:
      - application/json
      description: Returns user information based on their Email.
      parameters:
      - description: user email
        format: email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/dto.Account'
        "400":
          description: Invalid email
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn`t found.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Retrieve user by Email
      tags:
      - Account
  /id/account/new:
    post:
      consumes:
      - application/json
      description: Creates a new user and returns access tokens.
      parameters:
      - description: Data for creating a user
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUser'
      produces:
      - application/json
      responses:
        "201":
          description: Successful response with token
          schema:
            $ref: '#/definitions/dto.AccountAnswer'
        "400":
          description: Incorrect data
          schema:
            $ref: '#/definitions/resp.JsonError'
        "409":
          description: User with this email already exist
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      summary: Create User
      tags:
      - Account
  /id/auth/login:
    post:
      consumes:
      - application/json
      description: Logs in a user with email and password
      parameters:
      - description: Login information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Access token
          schema:
            $ref: '#/definitions/dto.Token'
        "400":
          description: Incorrect data
          schema:
            $ref: '#/definitions/resp.JsonError'
        "401":
          description: Incorrect email or password
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: This user wasn't found.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      summary: Log in a user
      tags:
      - Auth
  /id/auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out a user by invalidating the session
      produces:
      - application/json
      responses:
        "200":
          description: Logout success.
          schema:
            $ref: '#/definitions/resp.Message'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      security:
      - Bearer: []
      summary: Log out a user
      tags:
      - Auth
  /id/auth/refresh:
    get:
      consumes:
      - application/json
      description: Refreshes the user's tokens using the refresh token from the cookie
      produces:
      - application/json
      responses:
        "200":
          description: Refresh token
          schema:
            $ref: '#/definitions/dto.Token'
        "401":
          description: Token is invalid
          schema:
            $ref: '#/definitions/resp.JsonError'
        "404":
          description: Your token wasn't found., This user wasn't found.
          schema:
            $ref: '#/definitions/resp.JsonError'
        "500":
          description: Something going wrong...
          schema:
            $ref: '#/definitions/resp.JsonError'
      summary: Refresh user tokens
      tags:
      - Auth
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
