// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateBookingOperation         OperationName = "CreateBooking"
	CreateBookingForAdminOperation OperationName = "CreateBookingForAdmin"
	CreateOrderOperation           OperationName = "CreateOrder"
	DeleteBookingOperation         OperationName = "DeleteBooking"
	DeleteOrdersOperation          OperationName = "DeleteOrders"
	GetBookingByIdOperation        OperationName = "GetBookingById"
	GetFloorWorkloadOperation      OperationName = "GetFloorWorkload"
	GetWorkloadOperation           OperationName = "GetWorkload"
	ListAllBookingsOperation       OperationName = "ListAllBookings"
	ListMyBookingsOperation        OperationName = "ListMyBookings"
	ListOrdersOperation            OperationName = "ListOrders"
	UpdateBookingOperation         OperationName = "UpdateBooking"
)
