// Code generated by ogen, DO NOT EDIT.
package api

type CreateBookingForAdminRes interface {
	createBookingForAdminRes()
}

type CreateBookingRes interface {
	createBookingRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type DeleteBookingRes interface {
	deleteBookingRes()
}

type DeleteOrdersRes interface {
	deleteOrdersRes()
}

type GetBookingByIdRes interface {
	getBookingByIdRes()
}

type GetFloorWorkloadRes interface {
	getFloorWorkloadRes()
}

type GetWorkloadRes interface {
	getWorkloadRes()
}

type ListAllBookingsRes interface {
	listAllBookingsRes()
}

type ListMyBookingsRes interface {
	listMyBookingsRes()
}

type ListOrdersRes interface {
	listOrdersRes()
}

type UpdateBookingRes interface {
	updateBookingRes()
}
